name: Generate Whitelist

on:
  schedule:
    - cron: "0 0 * * 0"  # Weekly on Sunday at midnight UTC
  workflow_dispatch:     # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python Scripts/generate-whitelist.py

      - name: Commit and push if changed
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add whitelist.txt
          git diff --cached --quiet || git commit -m "Auto-update whitelist"
          
          # Debugging Step: Show the git repository URL
          echo "GitHub Repository URL: https://github.com/${{ github.repository }}"

          # Debugging Step: Print current branch
          echo "Current Branch: $(git branch --show-current)"

          # Debugging Step: Show remote settings
          git remote -v

          # Debugging Step: Check the status of the current branch
          git status

          # Debugging Step: Make sure the correct URL is being used
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
