name: Generate Whitelist

on:
  schedule:
    - cron: "0 0 * * 0"  # Weekly on Sunday at midnight UTC
  workflow_dispatch:     # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python Scripts/generate-whitelist.py

      - name: Commit and push if changed
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add whitelist.txt
          git diff --cached --quiet || git commit -m "Auto-update whitelist"

          # Pull the latest changes from the remote repository to avoid fast-forward errors
          git pull origin main --rebase

          # Push changes to the repository
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
