name: Generate Whitelist
on:
  schedule:
    - cron: "0 0 * * 0"  # Weekly on Sunday at midnight UTC
  workflow_dispatch:     # Manual trigger
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Run script
        run: python Scripts/generate-whitelist.py
      
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          
          # Add the changed file
          git add whitelist.txt
          
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          
          # Commit the changes
          git commit -m "Auto-update whitelist"
          
          # Try to push up to 3 times with fetch and rebase in between
          max_attempts=3
          attempt=1
          
          while [ $attempt -le $max_attempts ]; do
            echo "Push attempt $attempt of $max_attempts"
            
            # Try to push
            if git push origin main; then
              echo "Push successful!"
              exit 0
            fi
            
            echo "Push failed. Fetching latest changes and rebasing..."
            git fetch origin main
            git rebase origin/main
            
            # If there are conflicts, abort and try again from scratch
            if [ $? -ne 0 ]; then
              echo "Rebase had conflicts. Resetting..."
              git rebase --abort
              git reset --hard origin/main
              # Run the script again
              python Scripts/generate-whitelist.py
              git add whitelist.txt
              git commit -m "Auto-update whitelist"
            fi
            
            attempt=$((attempt+1))
          done
          
          echo "Failed to push after $max_attempts attempts"
          exit 1
